# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\add_scholarship.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addScholarshipForm(object):
    def setupUi(self, addScholarshipForm):
        addScholarshipForm.setObjectName("addScholarshipForm")
        addScholarshipForm.resize(351, 102)
        self.layoutWidget = QtWidgets.QWidget(addScholarshipForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_id_scholarship = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id_scholarship.sizePolicy().hasHeightForWidth())
        self.label_id_scholarship.setSizePolicy(sizePolicy)
        self.label_id_scholarship.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id_scholarship.setObjectName("label_id_scholarship")
        self.verticalLayout.addWidget(self.label_id_scholarship)
        self.label_name_scholarship = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_scholarship.sizePolicy().hasHeightForWidth())
        self.label_name_scholarship.setSizePolicy(sizePolicy)
        self.label_name_scholarship.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_scholarship.setObjectName("label_name_scholarship")
        self.verticalLayout.addWidget(self.label_name_scholarship)
        self.label_amount = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_amount.sizePolicy().hasHeightForWidth())
        self.label_amount.setSizePolicy(sizePolicy)
        self.label_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amount.setObjectName("label_amount")
        self.verticalLayout.addWidget(self.label_amount)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditIdScholarship = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditIdScholarship.setObjectName("lineEditIdScholarship")
        self.verticalLayout_2.addWidget(self.lineEditIdScholarship)
        self.lineEditNameScholarship = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNameScholarship.setObjectName("lineEditNameScholarship")
        self.verticalLayout_2.addWidget(self.lineEditNameScholarship)
        self.lineEditAmount = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.verticalLayout_2.addWidget(self.lineEditAmount)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pushButtonAddScholarship = QtWidgets.QPushButton(addScholarshipForm)
        self.pushButtonAddScholarship.setGeometry(QtCore.QRect(260, 20, 81, 41))
        self.pushButtonAddScholarship.setObjectName("pushButtonAddScholarship")

        self.retranslateUi(addScholarshipForm)
        QtCore.QMetaObject.connectSlotsByName(addScholarshipForm)

    def retranslateUi(self, addScholarshipForm):
        _translate = QtCore.QCoreApplication.translate
        addScholarshipForm.setWindowTitle(_translate("addScholarshipForm", "Добавление стипендии"))
        self.label_id_scholarship.setText(_translate("addScholarshipForm", "Id стипендии"))
        self.label_name_scholarship.setText(_translate("addScholarshipForm", "Название стипендии"))
        self.label_amount.setText(_translate("addScholarshipForm", "Размер"))
        self.pushButtonAddScholarship.setText(_translate("addScholarshipForm", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addScholarshipForm = QtWidgets.QWidget()
    ui = Ui_addScholarshipForm()
    ui.setupUi(addScholarshipForm)
    addScholarshipForm.show()
    sys.exit(app.exec_())
