# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\edit_debt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editDebtForm(object):
    def setupUi(self, editDebtForm):
        editDebtForm.setObjectName("editDebtForm")
        editDebtForm.resize(381, 132)
        self.layoutWidget = QtWidgets.QWidget(editDebtForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 249, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_gradebook = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gradebook.sizePolicy().hasHeightForWidth())
        self.label_gradebook.setSizePolicy(sizePolicy)
        self.label_gradebook.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gradebook.setObjectName("label_gradebook")
        self.verticalLayout.addWidget(self.label_gradebook)
        self.label_id_subject = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id_subject.sizePolicy().hasHeightForWidth())
        self.label_id_subject.setSizePolicy(sizePolicy)
        self.label_id_subject.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id_subject.setObjectName("label_id_subject")
        self.verticalLayout.addWidget(self.label_id_subject)
        self.label_semester = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_semester.sizePolicy().hasHeightForWidth())
        self.label_semester.setSizePolicy(sizePolicy)
        self.label_semester.setAlignment(QtCore.Qt.AlignCenter)
        self.label_semester.setObjectName("label_semester")
        self.verticalLayout.addWidget(self.label_semester)
        self.label_date = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.verticalLayout.addWidget(self.label_date)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditGradebook = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditGradebook.setObjectName("lineEditGradebook")
        self.verticalLayout_2.addWidget(self.lineEditGradebook)
        self.lineEditIdSubject = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditIdSubject.setObjectName("lineEditIdSubject")
        self.verticalLayout_2.addWidget(self.lineEditIdSubject)
        self.lineEditSemester = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditSemester.setObjectName("lineEditSemester")
        self.verticalLayout_2.addWidget(self.lineEditSemester)
        self.lineEditDate = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditDate.setObjectName("lineEditDate")
        self.verticalLayout_2.addWidget(self.lineEditDate)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pushButtonEditDebt = QtWidgets.QPushButton(editDebtForm)
        self.pushButtonEditDebt.setGeometry(QtCore.QRect(270, 40, 101, 41))
        self.pushButtonEditDebt.setObjectName("pushButtonEditDebt")

        self.retranslateUi(editDebtForm)
        QtCore.QMetaObject.connectSlotsByName(editDebtForm)

    def retranslateUi(self, editDebtForm):
        _translate = QtCore.QCoreApplication.translate
        editDebtForm.setWindowTitle(_translate("editDebtForm", "Редактирование"))
        self.label_gradebook.setText(_translate("editDebtForm", "№ зачётной книжки"))
        self.label_id_subject.setText(_translate("editDebtForm", "Id предмета"))
        self.label_semester.setText(_translate("editDebtForm", "Семестр"))
        self.label_date.setText(_translate("editDebtForm", "Дата"))
        self.pushButtonEditDebt.setText(_translate("editDebtForm", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editDebtForm = QtWidgets.QWidget()
    ui = Ui_editDebtForm()
    ui.setupUi(editDebtForm)
    editDebtForm.show()
    sys.exit(app.exec_())
