# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\edit_subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editSubjectForm(object):
    def setupUi(self, editSubjectForm):
        editSubjectForm.setObjectName("editSubjectForm")
        editSubjectForm.resize(371, 92)
        self.layoutWidget_2 = QtWidgets.QWidget(editSubjectForm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_number_subject = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_number_subject.sizePolicy().hasHeightForWidth())
        self.label_number_subject.setSizePolicy(sizePolicy)
        self.label_number_subject.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_subject.setObjectName("label_number_subject")
        self.verticalLayout_3.addWidget(self.label_number_subject)
        self.label_name_subject = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_subject.sizePolicy().hasHeightForWidth())
        self.label_name_subject.setSizePolicy(sizePolicy)
        self.label_name_subject.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_subject.setObjectName("label_name_subject")
        self.verticalLayout_3.addWidget(self.label_name_subject)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditIdSubject = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditIdSubject.setObjectName("lineEditIdSubject")
        self.verticalLayout_4.addWidget(self.lineEditIdSubject)
        self.lineEditNameSubject = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditNameSubject.setObjectName("lineEditNameSubject")
        self.verticalLayout_4.addWidget(self.lineEditNameSubject)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.pushButtonEditSubject = QtWidgets.QPushButton(editSubjectForm)
        self.pushButtonEditSubject.setGeometry(QtCore.QRect(260, 20, 101, 41))
        self.pushButtonEditSubject.setObjectName("pushButtonEditSubject")

        self.retranslateUi(editSubjectForm)
        QtCore.QMetaObject.connectSlotsByName(editSubjectForm)

    def retranslateUi(self, editSubjectForm):
        _translate = QtCore.QCoreApplication.translate
        editSubjectForm.setWindowTitle(_translate("editSubjectForm", "Редактирование"))
        self.label_number_subject.setText(_translate("editSubjectForm", "Id предмета"))
        self.label_name_subject.setText(_translate("editSubjectForm", "Название предмета"))
        self.pushButtonEditSubject.setText(_translate("editSubjectForm", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editSubjectForm = QtWidgets.QWidget()
    ui = Ui_editSubjectForm()
    ui.setupUi(editSubjectForm)
    editSubjectForm.show()
    sys.exit(app.exec_())
