# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\edit_scholarship.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editScholarshipForm(object):
    def setupUi(self, editScholarshipForm):
        editScholarshipForm.setObjectName("editScholarshipForm")
        editScholarshipForm.resize(371, 111)
        self.layoutWidget_2 = QtWidgets.QWidget(editScholarshipForm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_id_scholarship = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id_scholarship.sizePolicy().hasHeightForWidth())
        self.label_id_scholarship.setSizePolicy(sizePolicy)
        self.label_id_scholarship.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id_scholarship.setObjectName("label_id_scholarship")
        self.verticalLayout_3.addWidget(self.label_id_scholarship)
        self.label_name_scholarship = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_scholarship.sizePolicy().hasHeightForWidth())
        self.label_name_scholarship.setSizePolicy(sizePolicy)
        self.label_name_scholarship.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_scholarship.setObjectName("label_name_scholarship")
        self.verticalLayout_3.addWidget(self.label_name_scholarship)
        self.label_amount = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_amount.sizePolicy().hasHeightForWidth())
        self.label_amount.setSizePolicy(sizePolicy)
        self.label_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amount.setObjectName("label_amount")
        self.verticalLayout_3.addWidget(self.label_amount)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditIdScholarship = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditIdScholarship.setObjectName("lineEditIdScholarship")
        self.verticalLayout_4.addWidget(self.lineEditIdScholarship)
        self.lineEditNameScholarship = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditNameScholarship.setObjectName("lineEditNameScholarship")
        self.verticalLayout_4.addWidget(self.lineEditNameScholarship)
        self.lineEditAmount = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.verticalLayout_4.addWidget(self.lineEditAmount)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.pushButtonEditScholarship = QtWidgets.QPushButton(editScholarshipForm)
        self.pushButtonEditScholarship.setGeometry(QtCore.QRect(260, 30, 101, 41))
        self.pushButtonEditScholarship.setObjectName("pushButtonEditScholarship")

        self.retranslateUi(editScholarshipForm)
        QtCore.QMetaObject.connectSlotsByName(editScholarshipForm)

    def retranslateUi(self, editScholarshipForm):
        _translate = QtCore.QCoreApplication.translate
        editScholarshipForm.setWindowTitle(_translate("editScholarshipForm", "Редактирование"))
        self.label_id_scholarship.setText(_translate("editScholarshipForm", "Id стипендии"))
        self.label_name_scholarship.setText(_translate("editScholarshipForm", "Название стипендии"))
        self.label_amount.setText(_translate("editScholarshipForm", "Размер"))
        self.pushButtonEditScholarship.setText(_translate("editScholarshipForm", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editScholarshipForm = QtWidgets.QWidget()
    ui = Ui_editScholarshipForm()
    ui.setupUi(editScholarshipForm)
    editScholarshipForm.show()
    sys.exit(app.exec_())
