# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\edit_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editGroupForm(object):
    def setupUi(self, editGroupForm):
        editGroupForm.setObjectName("editGroupForm")
        editGroupForm.resize(371, 112)
        self.layoutWidget_2 = QtWidgets.QWidget(editGroupForm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_number_group = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_number_group.sizePolicy().hasHeightForWidth())
        self.label_number_group.setSizePolicy(sizePolicy)
        self.label_number_group.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_group.setObjectName("label_number_group")
        self.verticalLayout_3.addWidget(self.label_number_group)
        self.label_direction_training = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_direction_training.sizePolicy().hasHeightForWidth())
        self.label_direction_training.setSizePolicy(sizePolicy)
        self.label_direction_training.setAlignment(QtCore.Qt.AlignCenter)
        self.label_direction_training.setObjectName("label_direction_training")
        self.verticalLayout_3.addWidget(self.label_direction_training)
        self.label_course = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_course.sizePolicy().hasHeightForWidth())
        self.label_course.setSizePolicy(sizePolicy)
        self.label_course.setAlignment(QtCore.Qt.AlignCenter)
        self.label_course.setObjectName("label_course")
        self.verticalLayout_3.addWidget(self.label_course)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditNumberGroup = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditNumberGroup.setObjectName("lineEditNumberGroup")
        self.verticalLayout_4.addWidget(self.lineEditNumberGroup)
        self.lineEditDirectionTraining = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditDirectionTraining.setObjectName("lineEditDirectionTraining")
        self.verticalLayout_4.addWidget(self.lineEditDirectionTraining)
        self.lineEditCourse = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditCourse.setObjectName("lineEditCourse")
        self.verticalLayout_4.addWidget(self.lineEditCourse)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.pushButtonEditGroup = QtWidgets.QPushButton(editGroupForm)
        self.pushButtonEditGroup.setGeometry(QtCore.QRect(260, 30, 101, 41))
        self.pushButtonEditGroup.setObjectName("pushButtonEditGroup")

        self.retranslateUi(editGroupForm)
        QtCore.QMetaObject.connectSlotsByName(editGroupForm)

    def retranslateUi(self, editGroupForm):
        _translate = QtCore.QCoreApplication.translate
        editGroupForm.setWindowTitle(_translate("editGroupForm", "Редактирование"))
        self.label_number_group.setText(_translate("editGroupForm", "Номер группы"))
        self.label_direction_training.setText(_translate("editGroupForm", "Уровень обучения"))
        self.label_course.setText(_translate("editGroupForm", "Курс"))
        self.pushButtonEditGroup.setText(_translate("editGroupForm", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editGroupForm = QtWidgets.QWidget()
    ui = Ui_editGroupForm()
    ui.setupUi(editGroupForm)
    editGroupForm.show()
    sys.exit(app.exec_())
