# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\settings_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_groupForm(object):
    def setupUi(self, groupForm):
        groupForm.setObjectName("groupForm")
        groupForm.resize(271, 141)
        self.layoutWidget = QtWidgets.QWidget(groupForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 131, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_number_group = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_number_group.sizePolicy().hasHeightForWidth())
        self.checkBox_number_group.setSizePolicy(sizePolicy)
        self.checkBox_number_group.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_number_group.setObjectName("checkBox_number_group")
        self.verticalLayout_2.addWidget(self.checkBox_number_group)
        self.checkBox_direction_training = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_direction_training.sizePolicy().hasHeightForWidth())
        self.checkBox_direction_training.setSizePolicy(sizePolicy)
        self.checkBox_direction_training.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_direction_training.setObjectName("checkBox_direction_training")
        self.verticalLayout_2.addWidget(self.checkBox_direction_training)
        self.checkBox_course = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_course.sizePolicy().hasHeightForWidth())
        self.checkBox_course.setSizePolicy(sizePolicy)
        self.checkBox_course.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_course.setObjectName("checkBox_course")
        self.verticalLayout_2.addWidget(self.checkBox_course)
        self.pushButtonApplySettingsGroup = QtWidgets.QPushButton(groupForm)
        self.pushButtonApplySettingsGroup.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.pushButtonApplySettingsGroup.setObjectName("pushButtonApplySettingsGroup")

        self.retranslateUi(groupForm)
        QtCore.QMetaObject.connectSlotsByName(groupForm)

    def retranslateUi(self, groupForm):
        _translate = QtCore.QCoreApplication.translate
        groupForm.setWindowTitle(_translate("groupForm", "Настройка отображения"))
        self.checkBox_number_group.setText(_translate("groupForm", "Номер группы"))
        self.checkBox_direction_training.setText(_translate("groupForm", "Уровень обучения"))
        self.checkBox_course.setText(_translate("groupForm", "Курс"))
        self.pushButtonApplySettingsGroup.setText(_translate("groupForm", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    groupForm = QtWidgets.QWidget()
    ui = Ui_groupForm()
    ui.setupUi(groupForm)
    groupForm.show()
    sys.exit(app.exec_())
