# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\settings_debt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_debtForm(object):
    def setupUi(self, debtForm):
        debtForm.setObjectName("debtForm")
        debtForm.resize(281, 161)
        self.layoutWidget = QtWidgets.QWidget(debtForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 141, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_id_debt = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_id_debt.sizePolicy().hasHeightForWidth())
        self.checkBox_id_debt.setSizePolicy(sizePolicy)
        self.checkBox_id_debt.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_id_debt.setObjectName("checkBox_id_debt")
        self.verticalLayout_2.addWidget(self.checkBox_id_debt)
        self.checkBox_gradebook = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_gradebook.sizePolicy().hasHeightForWidth())
        self.checkBox_gradebook.setSizePolicy(sizePolicy)
        self.checkBox_gradebook.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_gradebook.setObjectName("checkBox_gradebook")
        self.verticalLayout_2.addWidget(self.checkBox_gradebook)
        self.checkBox_id_subject = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_id_subject.sizePolicy().hasHeightForWidth())
        self.checkBox_id_subject.setSizePolicy(sizePolicy)
        self.checkBox_id_subject.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_id_subject.setObjectName("checkBox_id_subject")
        self.verticalLayout_2.addWidget(self.checkBox_id_subject)
        self.checkBox_semester = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_semester.sizePolicy().hasHeightForWidth())
        self.checkBox_semester.setSizePolicy(sizePolicy)
        self.checkBox_semester.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_semester.setObjectName("checkBox_semester")
        self.verticalLayout_2.addWidget(self.checkBox_semester)
        self.checkBox_date = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_date.sizePolicy().hasHeightForWidth())
        self.checkBox_date.setSizePolicy(sizePolicy)
        self.checkBox_date.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_date.setObjectName("checkBox_date")
        self.verticalLayout_2.addWidget(self.checkBox_date)
        self.pushButtonApplySettingsDebt = QtWidgets.QPushButton(debtForm)
        self.pushButtonApplySettingsDebt.setGeometry(QtCore.QRect(170, 50, 101, 31))
        self.pushButtonApplySettingsDebt.setObjectName("pushButtonApplySettingsDebt")

        self.retranslateUi(debtForm)
        QtCore.QMetaObject.connectSlotsByName(debtForm)

    def retranslateUi(self, debtForm):
        _translate = QtCore.QCoreApplication.translate
        debtForm.setWindowTitle(_translate("debtForm", "Настройки столбцов"))
        self.checkBox_id_debt.setText(_translate("debtForm", "Id долга"))
        self.checkBox_gradebook.setText(_translate("debtForm", "№ зачётной книжки"))
        self.checkBox_id_subject.setText(_translate("debtForm", "Id предмета"))
        self.checkBox_semester.setText(_translate("debtForm", "Семестр"))
        self.checkBox_date.setText(_translate("debtForm", "Дата"))
        self.pushButtonApplySettingsDebt.setText(_translate("debtForm", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    debtForm = QtWidgets.QWidget()
    ui = Ui_debtForm()
    ui.setupUi(debtForm)
    debtForm.show()
    sys.exit(app.exec_())
