# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\course work\pop_up_windows\settings_subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subjectForm(object):
    def setupUi(self, subjectForm):
        subjectForm.setObjectName("subjectForm")
        subjectForm.resize(271, 92)
        self.layoutWidget = QtWidgets.QWidget(subjectForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_id_subject = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_id_subject.sizePolicy().hasHeightForWidth())
        self.checkBox_id_subject.setSizePolicy(sizePolicy)
        self.checkBox_id_subject.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_id_subject.setObjectName("checkBox_id_subject")
        self.verticalLayout_2.addWidget(self.checkBox_id_subject)
        self.checkBox_name_subject = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_name_subject.sizePolicy().hasHeightForWidth())
        self.checkBox_name_subject.setSizePolicy(sizePolicy)
        self.checkBox_name_subject.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(89, 170, 139);")
        self.checkBox_name_subject.setObjectName("checkBox_name_subject")
        self.verticalLayout_2.addWidget(self.checkBox_name_subject)
        self.pushButtonApplySettingsSubject = QtWidgets.QPushButton(subjectForm)
        self.pushButtonApplySettingsSubject.setGeometry(QtCore.QRect(160, 20, 101, 31))
        self.pushButtonApplySettingsSubject.setObjectName("pushButtonApplySettingsSubject")

        self.retranslateUi(subjectForm)
        QtCore.QMetaObject.connectSlotsByName(subjectForm)

    def retranslateUi(self, subjectForm):
        _translate = QtCore.QCoreApplication.translate
        subjectForm.setWindowTitle(_translate("subjectForm", "Настройка отображения"))
        self.checkBox_id_subject.setText(_translate("subjectForm", "Id предмета"))
        self.checkBox_name_subject.setText(_translate("subjectForm", "Название предмета"))
        self.pushButtonApplySettingsSubject.setText(_translate("subjectForm", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subjectForm = QtWidgets.QWidget()
    ui = Ui_subjectForm()
    ui.setupUi(subjectForm)
    subjectForm.show()
    sys.exit(app.exec_())
